name: Build and deploy Python app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ruff
        uses: astral-sh/ruff-action@v3
        with: 
          src: "./api"
      - run: ruff check --fix api/
      - run: ruff format api/

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (check)
        run: pip install -r requirements.txt

      - name: Run tests
        run: |
            export PYTHONPATH=$(pwd)
            pytest --maxfail=1 --disable-warnings -q api/tests_unitaires

  build:
    runs-on: ubuntu-latest
    needs: [lint-format, unit-tests]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip app files (exclude .git, .github)
        run: zip -r release.zip . -x ".git/*" ".github/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
      
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app
          
      - name: Unzip artifact
        run: unzip release.zip
        
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E580BAF37D8F445DA2C204A99CFF3EAE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AA991A1A26764C7A82524121484E31FB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A541A9015A3D43D6AA32C85D8274DDE6 }}
     
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'projet7-credit-default-risk'
          slot-name: 'Production'

